# Generated by Django 2.2.5 on 2019-12-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberAccount', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('uname', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
