# Generated by Django 2.2.5 on 2019-12-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='uname',
        ),
    ]
