# Generated by Django 2.2.5 on 2019-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=15)),
                ('ProductId', models.CharField(max_length=15)),
                ('ProductName', models.CharField(max_length=15)),
                ('MarketId', models.CharField(max_length=15)),
                ('MarketName', models.CharField(max_length=15)),
                ('AveragePrice', models.FloatField()),
            ],
        ),
    ]
