# Generated by Django 2.2.5 on 2019-12-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarketNum', models.CharField(max_length=15)),
                ('MarketName', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MarketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNum', models.CharField(max_length=15)),
                ('ProductName', models.CharField(max_length=15)),
                ('market_pro', models.ManyToManyField(related_name='market_product', through='products.MarketProduct', to='products.Market')),
            ],
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='fav',
            field=models.ManyToManyField(related_name='favorite_pro', through='products.Favorite', to='members.Member'),
        ),
        migrations.AddField(
            model_name='marketproduct',
            name='price',
            field=models.ManyToManyField(related_name='price_pro', through='products.CurrentPrice', to='products.Date'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='MPId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MarketProduct'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='MemberId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
        ),
        migrations.AddField(
            model_name='currentprice',
            name='Day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Date'),
        ),
        migrations.AddField(
            model_name='currentprice',
            name='MPId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.MarketProduct'),
        ),
    ]
